### ISSUE TITLE
[Front-End] What a Event Page should look like including review and promote function

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#25]
![jogging_event](https://user-images.githubusercontent.com/44449668/74278068-99846080-4ce6-11ea-9171-b4c43613504d.png)

**Comment by RobertZSun** [comment]
@mhassany could you please to give a hand working on this feature?

**Comment by mhassany** [comment]
Hi,

I created the html structure of this page, but because i am waiting for database schema file I have not added the ui logic to make them intractable. 
below is an screenshot of the finished ui.

![Screen Shot 2020-02-12 at 5 22 42 PM](https://user-images.githubusercontent.com/44843729/74384134-a4aabf80-4dbe-11ea-9365-51565bb3a7d1.png)

**Comment by RobertZSun** [comment]
Perfect Job!

**Comment by mhassany** [comment]
[complete] event, and review can be created and edited in this [pull request](https://github.com/bestksl/SSW695/pull/91)
