### ISSUE TITLE
[Front-End] Create the Event Page template for hold all the info that an event needs

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#8]

**Comment by RobertZSun** [comment]
![create_a_event](https://user-images.githubusercontent.com/44449668/73689167-a3311700-469b-11ea-8a15-0b58ee266d01.png)

**Comment by RobertZSun** [comment]
@mhassany please work on this

**Comment by mhassany** [comment]
Hi,

I created the html structure of this page, but because i am waiting for database schema file I have not added the ui logic to make them intractable.
below is an screenshot of the finished ui.

![Screen Shot 2020-02-12 at 5 22 18 PM](https://user-images.githubusercontent.com/44843729/74384403-2995d900-4dbf-11ea-9f99-34296552e2a2.png)

**Comment by mhassany** [comment]
implemented.
